skyzh/mini-lsm

mini-lsm-starter/src/mem_table.rs

The tempfile dependency causes build failure due to being in dev-dependencies. Adding cfg(test) fixes the isseue.

Add cfg(test) to mod tests in mem_table.rs.

---

mini-lsm-book/src/01-block.md

Fixed typo: varlen -> keylen

---

rust-toolchain.toml

run command `cargo x install-tools` will get this error:
```
package `anstream v0.6.5` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.66.1
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p anstream@0.6.5 --precise ver
where `ver` is the latest version of `anstream` supporting rustc 1.66.1
```
I update my rustc version, it turns out that this file use older rustc version.
I prefer to use latest stable version which is `1.74.1`, but `1.70.0` is enough to solve this problem.

update rustc version

---

mini-lsm/src/tests/week1_day2.rs

Previously a bad impl won't panic, because the heap only have one iter.

test: improve week1_day2::test_task2_merge_error

---

mini-lsm/src/tests/week1_day5.rs

Add a case when scan with an exclusive start where the start key locates on a sstable

test: test scan exclusive start on a sstable

---

mini-lsm-book/src/week2-03-tiered.md

I think the description in md:
https://github.com/skyzh/mini-lsm/blob/2015ee17032b551d964b5f9fbb8d1ff2165673de/mini-lsm-book/src/week2-03-tiered.md?plain=1#L79
"num_iter" and "iter" should be "num_tier" and "tier" 
as in the code:
https://github.com/skyzh/mini-lsm/blob/2015ee17032b551d964b5f9fbb8d1ff2165673de/mini-lsm-starter/src/bin/mini-lsm-cli.rs#L330

fix: typo in md (iter->tier)

---

mini-lsm-starter/src/bin/mini-lsm-cli.rs

When executing `close` command in cli repl, mini lsm should call its `close` function to update state and manifest.

fix: call lsm::close when closing the cli

---

mini-lsm-book/src/week3-05-txn-occ.md
mini-lsm-mvcc/src/mvcc/txn.rs
mini-lsm-starter/src/mvcc/txn.rs

Pretty trivial fixes of typos.

Fix typos in W3D5 writeup and code

---

mini-lsm-book/src/week1-06-write-path.md

"two" things -> "three" things
https://github.com/skyzh/mini-lsm/blob/bcaab6f706cb33ebaea6a1f00c444f84d924f309/mini-lsm-book/src/week1-06-write-path.md?plain=1#L29-L33

[fix]: Fix typo in w1d6

---

mini-lsm-mvcc/src/compact.rs
mini-lsm-mvcc/src/iterators/merge_iterator.rs
mini-lsm-mvcc/src/key.rs
mini-lsm-mvcc/src/mem_table.rs
mini-lsm-mvcc/src/table/bloom.rs
mini-lsm-starter/src/iterators/merge_iterator.rs
mini-lsm-starter/src/table/bloom.rs
mini-lsm/src/compact.rs
mini-lsm/src/iterators/merge_iterator.rs
mini-lsm/src/table/bloom.rs

- [`non_canonical_partial_ord_impl`](https://rust-lang.github.io/rust-clippy/master/index.html#/non_canonical_partial_ord_impl)
It seems like `partial_cmp` never return `None`, so I made small change of it.
The new implementation has a small logic change from the previous one, since arguments passed to [`Ordering::then`](https://doc.rust-lang.org/std/cmp/enum.Ordering.html#method.then) are eagerly evaluated.
I pefer it because it's more succinct than [`Ordering::then_with`](https://doc.rust-lang.org/std/cmp/enum.Ordering.html#method.then_with) and without notable performace penalty. That's enough for an educational project.
- [`manual_clamp`](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_clamp)
---
My rust version is `rustc 1.79.0 (129f3b996 2024-06-10)`, so there are …

Fix some clippy lint.

---

mini-lsm-mvcc/src/compact.rs
mini-lsm-mvcc/src/compact/leveled.rs
mini-lsm-mvcc/src/lsm_storage.rs
mini-lsm-starter/src/bin/compaction-simulator.rs
mini-lsm-starter/src/compact.rs
mini-lsm-starter/src/compact/leveled.rs
mini-lsm/src/compact.rs
mini-lsm/src/compact/leveled.rs
mini-lsm/src/lsm_storage.rs
mini-lsm/src/tests/week2_day5.rs

Fixes #62 
- Add a test case to capture the error
Below is what the test failure looks like on old version of the code:
```Bash
--- STDERR:              mini-lsm tests::week2_day5::test_multiple_compacted_ssts_leveled ---
thread 'tests::week2_day5::test_multiple_compacted_ssts_leveled' panicked at mini-lsm/src/compact/leveled.rs:223:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
- Fix the error by moving the sorting logic outside of `apply_compaction_result` into `trigger_compaction`

fix: Avoid leveled compaction crash when recovering from manifest

---

mini-lsm-book/src/week2-05-manifest.md
mini-lsm-mvcc/src/lsm_storage.rs
mini-lsm/src/lsm_storage.rs

ref https://github.com/skyzh/mini-lsm/pull/63

docs: add recovery mode for leveled compaction

---

mini-lsm-mvcc/src/compact/tiered.rs
mini-lsm-mvcc/src/table/bloom.rs
mini-lsm-starter/src/bin/compaction-simulator.rs
mini-lsm-starter/src/bin/mini-lsm-cli.rs
mini-lsm-starter/src/compact/tiered.rs
mini-lsm-starter/src/table/bloom.rs
mini-lsm/src/compact/tiered.rs
mini-lsm/src/table/bloom.rs
mini-lsm/src/tests/harness.rs
mini-lsm/src/tests/week2_day3.rs
mini-lsm/src/tests/week2_day5.rs
mini-lsm/src/tests/week2_day6.rs

close https://github.com/skyzh/mini-lsm/issues/96
the original condition was not very correct and would produce larger write amplification, so we make it exactly the same as RocksDB in this PR. TODO: fix doc and tests.

fix: universal compaction condition

---

mini-lsm-book/src/week1-02-merge-iterator.md

This part of the exercise took my a while to grok. Adding more context to explain the binary heap.

Clarify more about the binary heap

---

mini-lsm-mvcc/src/compact/simple_leveled.rs
mini-lsm/src/compact/simple_leveled.rs

fix(compaction): correct level0_file_num_compaction_trigger in simple leveled compaction

---

mini-lsm-starter/src/wal.rs

Removes a duplicate attribute, as reported by Clippy.

chore: remove a duplicate attribute

---

mini-lsm-mvcc/src/lsm_storage.rs

Put data one by one makes WAL's atomicity ineffective. A batch of data modified by the same transaction should be regarded as a whole.

make write batch aotmic under txn sys

---

mini-lsm-book/src/week3-05-txn-occ.md

If the LsmStorageInner::write_batch is not modified, the atomicity of the WAL cannot be guaranteed.

book: ‎LsmStorageInner::write_batch ‎method should be modified to call MemTable::put_batch

---

mini-lsm-starter/src/lsm_storage.rs
mini-lsm-starter/src/mvcc.rs
mini-lsm-starter/src/mvcc/watermark.rs

The test of w3d4 uses methods that do not exist in mini-lsm-starter.

sync: synchronize the methods used in the w3d4 test to mini-lsm-starter

---

mini-lsm-book/src/week1-02-merge-iterator.md

Improves the documentation for the "Merge Iterator" chapter:
- For MergeIterator, the explanation for using a binary heap is made more heuristic, linking it to the problem of merging `n` sorted sequences. This provides better intuition for the choice.
- Add reference for the `ouroboros` crate, closes #109

docs: clarify MergeIterator heap rationale and ouroboros usage

---

mini-lsm-starter/src/mem_table.rs
mini-lsm-starter/src/wal.rs
mini-lsm/src/mem_table.rs
mini-lsm/src/wal.rs

Fix wrong input type of put_batch
